version: '1'
services:
  app:
    container_name: nginxproxymanager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - .nginxdata:/data
      - .nginxdata/letsencrypt:/etc/letsencrypt
